digitalocean_api_token: "dop_v1_b4e4475588c2b8b3d76e5e5a0d073a62c59dd2cb7e7549a3bc253851b3e74e13"
droplet_name: "my-droplet"
droplet_region: "nyc3"
droplet_size: "s-1vcpu-1gb"
droplet_image: "ubuntu-20-04-x64"
droplet_ssh_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRhV/doPbPwnl4x6bq8Qf59uffI6IUtslIVHVA+A/CHPEnz0P6vCGeEHtuuFInvHsBARbTS6OAYMU4k8oNxKcmShssUl53SmSM5KUd4myIVp7bPA7uIqFRULLsZv2QIum5E8vvYGGWErbrhaBvRZnnC05mk/41eO0JEMFo/TL/5TnsIJANkW2bpDRlAtLL1CxdbJf3Au/IIfclnYR9IF7u1WIwrcN/jr5js0RrevNCO7gxwm4HS4jFR65f+s8Jh68CMXmK6ATH5zemTVENjsoXsnIbMdvMhQWViEago/DILEF6hiyVWH4fHDPdkugNWnIIAIUYqz6EQN2X7bUg9jKR9BwDP6Oh5Z5g+fYgYZ4EZy5YwOgeVAxCIyoDo+ndH8o2LJe2S/qO+mpFYPghxjC8wBXH5zAryfa/xw78Mf7bEHpva3KeV+JPVUdSTpUCS9yEWJetFXKUFUxsB/G1w68Ma4QfR4qpFZ9wQHs1kB5TKeve/WEwDvZvkkKAEeDeclk= root@68a99eca4c70"