---
- name: Create a DigitalOcean Droplet
  hosts: localhost
  gather_facts: no
  vars_files:
    - resources/ansible/group_vars/development.yml
  tasks:
    - name: Create a new Droplet
      community.digitalocean.digital_ocean_droplet:
        state: present
        api_token: "{{ digitalocean_api_token }}"
        name: "{{ droplet_name }}"
        region: "{{ droplet_region }}"
        size: "{{ droplet_size }}"
        image: "{{ droplet_image }}"
        ssh_keys: "{{ droplet_ssh_keys }}"
      register: droplet

    - name: Output the Droplet IP address
      debug:
        msg: "Droplet IP address is {{ droplet.data.ip_address }}"