---
- name: Install and configure Nginx
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true
