---
- name: Install RKE2
  hosts: all
  become: true
  tasks:
    - name: Add RKE2 repository
      shell: |
        curl -sfL https://get.rke2.io | sh -
      args:
        creates: /usr/local/bin/rke2

    - name: Enable and start RKE2 server
      systemd:
        name: rke2-server
        enabled: yes
        state: started
      notify: Restart RKE2 server

    - name: Wait for RKE2 to be ready
      shell: |
        while ! systemctl is-active rke2-server; do
          echo "Waiting for RKE2 server to be active..."
          sleep 1
        done
      retries: 30
      delay: 10
      register: rke2_status
      until: rke2_status.rc == 0

    - name: Copy kubeconfig to user home
      copy:
        src: /etc/rancher/rke2/rke2.yaml
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        mode: '0644'
      become: true
      become_user: "{{ ansible_user }}"