---
- name: Install and configure RKE2
  hosts: all
  become: true
  tasks:
    - name: Add RKE2 repository and install RKE2
      shell: |
        curl -sfL https://get.rke2.io | sh -
      args:
        creates: /usr/local/bin/rke2

    - name: Enable and start RKE2 server
      systemd:
        name: rke2-server
        enabled: yes
        state: started
      notify: Restart RKE2 server

    - name: Wait for RKE2 to be active
      shell: |
        while ! systemctl is-active rke2-server; do sleep 1; done
      retries: 10
      delay: 5
      register: rke2_status
      until: rke2_status.rc == 0

    - name: Ensure .kube directory exists
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy kubeconfig to user home
      copy:
        src: /etc/rancher/rke2/rke2.yaml
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        mode: '0644'
      become: true
      become_user: "{{ ansible_user }}"

  handlers:
    - name: Restart RKE2 server
      systemd:
        name: rke2-server
        state: restarted
